// GENERATED by koperca-sdlc — vendored by adopt.sh.
//
// Conventional Commits are not cosmetics here: gates/promote.sh derives release
// notes, and ship-metrics.mjs derives change-type breakdowns, from the subject
// line. An unparseable history means an unmeasurable delivery process.

module.exports = {
  extends: [],
  parserPreset: {
    parserOpts: { headerPattern: /^(\w+)(?:\(([^)]+)\))?!?: (.+)$/, headerCorrespondence: ['type', 'scope', 'subject'] },
  },
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'refactor',
        'test',
        'docs',
        'build',
        'ci',
        'chore',
        'revert',
        'sdlc', // harness adoption/upgrade commits — kept separate so they can be
                // filtered out of lead-time and change-failure statistics
      ],
    ],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 100],
  },
};
