// GENERATED by koperca-sdlc v1 — shim only.
// The rules live in koperca-sdlc/configs/eslint/ so one install pins one
// version of every plugin fleet-wide. Repo-specific exceptions go in the
// exported array below, never by editing the preset.
import { homedir } from 'node:os';
import { join } from 'node:path';

const sdlc = process.env.KOPERCA_SDLC ?? join(homedir(), 'repos/koperca-sdlc');
const { nestConfig } = await import(
  join(sdlc, 'configs/eslint/nest.mjs')
);

export default [
  ...nestConfig({ tsconfig: 'tsconfig.json' }),
  // ── repo-specific exceptions (justify each one) ──
  {
    // cjs config files are not in tsconfig, so the typed parser cannot lint
    // them (they currently fail with PARSE errors).
    ignores: ['commitlint.config.cjs', 'jest.config.cjs', 'prettier.config.cjs'],
  },
  {
    // PrismaService IS the repository boundary the no-restricted-imports rule
    // protects — it must import @prisma/client to extend PrismaClient.
    files: ['src/modules/prisma/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },
];
