// GENERATED by koperca-sdlc v1 — shim only.
// The rules live in koperca-sdlc/configs/eslint/ so one install pins one
// version of every plugin fleet-wide. Repo-specific exceptions go in the
// exported array below, never by editing the preset.
import { homedir } from 'node:os';
import { join } from 'node:path';

const sdlc = process.env.KOPERCA_SDLC ?? join(homedir(), 'repos/koperca-sdlc');
const { nestConfig } = await import(
  join(sdlc, 'configs/eslint/nest.mjs')
);

export default [
  ...nestConfig({ tsconfig: 'tsconfig.json' }),
  // ── repo-specific exceptions (justify each one) ──
];
