// GENERATED by koperca-sdlc — vendored by adopt.sh.
// Matches the .prettierrc already used across the Nest repos so adoption is not
// a fleet-wide reformat commit.
module.exports = {
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 100,
  tabWidth: 2,
  semi: true,
  endOfLine: 'lf',
  overrides: [{ files: '*.svelte', options: { parser: 'svelte' } }],
};
